# Generated by Django 5.2.10 on 2026-01-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Telegram chat id"
            ),
        ),
    ]
