# Generated by Django 6.0.1 on 2026-01-20 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите место", max_length=255, verbose_name="Место"
                    ),
                ),
                (
                    "time",
                    models.TimeField(help_text="Укажите время", verbose_name="Время"),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие",
                        max_length=255,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_enjoyable_habit",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите признак приятной привычки",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Укажите периодичность привычки",
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        help_text="Укажите время на выполнение",
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Публичный"), ("private", "Частный")],
                        help_text="Выберите признак публичности",
                        max_length=7,
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите связанную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_to",
                        to="daily_tracker.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
