# Generated by Django 5.2.10 on 2026-01-26 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_tracker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="habit",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_enjoyable_habit",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_to",
                to="daily_tracker.habit",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(blank=True, default=" ", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Публичный"), ("private", "Частный")],
                default="private",
                max_length=7,
            ),
        ),
    ]
