# Generated by Django 5.2.10 on 2026-01-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_tracker", "0002_alter_habit_action_alter_habit_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_sent",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата последнего напоминания"
            ),
        ),
    ]
